### PR TITLE
Separate widget templates

### PR DESCRIPTION
**Pull request by ulope**
Implements the design from #120.
Includes docs & tests

### CODE REVIEW

**Comment by gregmuellegger** [comment]
You, Sir, are my hero! Thank you soo much for stepping up and implementing this. I will try to get a new release ready soonish so that everyone can benefit from it.

**Comment by ulope** [comment]
You are very welcome :) Thanks for merging it so quickly.

**Comment by gregmuellegger** [comment]
I cannot resist if the patch even contains docs and tests. It's a pleasure! :)

**Comment by gregmuellegger** [comment]
I just released django-floppyforms 1.4.0 which contains your changes. Thanks so much for your work!
https://pypi.python.org/pypi/django-floppyforms/

**Pull request merged**
